deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -84,40 +84,43 @@ jobs:
         working-directory: terraform
         run: terraform apply -auto-approve
 
-      - name: Wait for EC2 to be ready & Get Public IP
+      - name: Wait for EC2 and Fetch Public IP
         id: ec2_ip
         run: |
+          INSTANCE_ID=$(aws ec2 describe-instances \
+            --filters "Name=tag:Name,Values=webserver" \
+            --query "Reservations[*].Instances[0].InstanceId" \
+            --output text)
+      
+          echo "Instance ID: $INSTANCE_ID"
+      
+          if [ -z "$INSTANCE_ID" ]; then
+            echo "❌ ERROR: No instance found with tag Name=webserver!"
+            exit 1
+          fi
+      
           echo "Waiting for EC2 instance to be in 'running' state..."
-          while true; do
-            STATE=$(aws ec2 describe-instances \
-              --filters "Name=tag:Name,Values=webserver" \
-              --query "Reservations[*].Instances[0].State.Name" \
-              --output text)
-            if [[ "$STATE" == "running" ]]; then
-              echo "✅ EC2 is running!"
-              break
-            fi
-            echo "⏳ Still initializing... waiting 100s"
-            sleep 100
-          done
-
+          aws ec2 wait instance-running --instance-ids "$INSTANCE_ID"
+      
+          echo "✅ EC2 is now running!"
+      
           echo "Fetching Public IP..."
           while true; do
             IP=$(aws ec2 describe-instances \
-              --filters "Name=tag:Name,Values=webserver" \
+              --instance-ids "$INSTANCE_ID" \
               --query "Reservations[*].Instances[0].PublicIpAddress" \
               --output text)
+      
             if [[ "$IP" != "None" && -n "$IP" ]]; then
               echo "✅ EC2 Public IP: $IP"
               echo "EC2_IP=$IP" >> $GITHUB_ENV
               break
             fi
-            echo "⏳ Public IP not assigned yet... waiting 100s"
-            sleep 100
+      
+            echo "⏳ Public IP not assigned yet... waiting 5s"
+            sleep 5
           done
         shell: bash
-
-
 
   ansible:
     name: Configure EC2 with Ansible
